//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LECommonLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LECommonLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LERegistry&gt;
        ///  &lt;Entries&gt;
        ///    &lt;Entry Root=&quot;HKEY_LOCAL_MACHINE&quot; Key=&quot;System\CurrentControlSet\Control\Nls\CodePage&quot; Name=&quot;ACP&quot; Type=&quot;REG_SZ&quot;&gt;
        ///      &lt;Data&gt;932&lt;/Data&gt;
        ///    &lt;/Entry&gt;
        ///    &lt;Entry Root=&quot;HKEY_LOCAL_MACHINE&quot; Key=&quot;System\CurrentControlSet\Control\Nls\CodePage&quot; Name=&quot;OEMCP&quot; Type=&quot;REG_SZ&quot;&gt;
        ///      &lt;Data&gt;932&lt;/Data&gt;
        ///    &lt;/Entry&gt;
        ///    &lt;Entry Root=&quot;HKEY_LOCAL_MACHINE&quot; Key=&quot;System\CurrentControlSet\Control\Nls\Language&quot; Name=&quot;Default&quot; Type=&quot;REG_SZ&quot;&gt;
        ///      &lt;Data&gt;1041&lt;/Data&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LERegistry {
            get {
                return ResourceManager.GetString("LERegistry", resourceCulture);
            }
        }
    }
}
